backend:
  name: github
  repo: hrfmmymt/astro-sample
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://tiny-belekoy-1ca787.netlify.app/"

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: pubDate, label: Date, widget: date }
      # - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      # - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }